(function(){
  var DATA={"robot-aspirapolvere":{"nome":"Robot aspirapolvere","singolare":"robot aspirapolvere","scelta":"Roborock S8 MaxV Ultra","img":"https://m.media-amazon.com/images/I/71ZCXAWP1uL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/robot-aspirapolvere/?ref=widget"},"sedie-ergonomiche":{"nome":"Sedie ergonomiche","singolare":"sedia da ufficio","scelta":"CLOUVOU CLOUVOU CleverSeat lombare adattivo 4D","img":"https://m.media-amazon.com/images/I/81TpUJ-uT1L._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/sedie-ergonomiche/?ref=widget"},"materassi":{"nome":"Materassi","singolare":"materasso","scelta":"Comfy Line Comfy Line Elisir Waterfoam 20 cm 80x190","img":"https://m.media-amazon.com/images/I/91Ewcby2vsL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/materassi/?ref=widget"},"utensili-elettrici":{"nome":"Trapani e avvitatori","singolare":"trapano","scelta":"Bosch Professional Bosch GSR 12V-15 (2x2,0 Ah + 39 accessori)","img":"https://m.media-amazon.com/images/I/71BZCpITTYL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/utensili-elettrici/?ref=widget"},"macchine-caffe":{"nome":"Macchine da caffè","singolare":"macchina da caffè","scelta":"De'Longhi Rivelia","img":"https://m.media-amazon.com/images/I/613IBmDZnOL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/macchine-caffe/?ref=widget"},"scrivanie-regolabili":{"nome":"Scrivanie regolabili","singolare":"scrivania regolabile in altezza","scelta":"Raplink Raplink HTK-4540 120x60 elettrica","img":"https://m.media-amazon.com/images/I/71VTEFVhuCL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/scrivanie-regolabili/?ref=widget"},"deumidificatori":{"nome":"Deumidificatori","singolare":"deumidificatore","scelta":"Comfee Comfee' MDDF-16DEN7 WF 16L","img":"https://m.media-amazon.com/images/I/51o1O6UT3DL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/deumidificatori/?ref=widget"},"obiettivi-fotografici":{"nome":"Obiettivi fotografici","singolare":"obiettivo fotografico","scelta":"Sigma Sigma 18-50mm f/2.8 DC DN Contemporary (Sony E)","img":"https://m.media-amazon.com/images/I/516w4AjhV5L._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/obiettivi-fotografici/?ref=widget"},"friggitrici-aria":{"nome":"Friggitrici ad aria","singolare":"friggitrice ad aria","scelta":"Cosori Cosori Dual Zone 8,5 L CAF-R903","img":"https://m.media-amazon.com/images/I/61m0LtJ-nNL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/friggitrici-aria/?ref=widget"},"monitor-scrivania":{"nome":"Monitor da scrivania","singolare":"monitor","scelta":"AOC AOC 24G42E","img":"https://m.media-amazon.com/images/I/71oKxc7WIoL._AC_SL400_.jpg","url":"https://www.pickforme.it/categoria/monitor-scrivania/?ref=widget"}};
  var BASE="https://www.pickforme.it";
  var s=document.currentScript;if(!s){var ss=document.getElementsByTagName('script');s=ss[ss.length-1];}
  var cat=s.getAttribute('data-categoria');var d=DATA[cat];
  var box=document.createElement('div');
  box.setAttribute('style','all:initial;display:block;max-width:360px;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;border:1px solid #e6e7ea;border-radius:16px;overflow:hidden;box-shadow:0 12px 30px -18px rgba(16,24,40,.35);background:#fff');
  var head='<div style="background:linear-gradient(135deg,#F04518,#FE6E2A);color:#fff;padding:11px 15px;font-weight:800;font-size:14px;letter-spacing:-.01em">PickForMe · la scelta giusta</div>';
  var body;
  if(d){
    body='<div style="padding:15px">'+(d.img?'<div style="background:#f5f5f6;border-radius:10px;height:150px;display:flex;align-items:center;justify-content:center;padding:12px;margin-bottom:12px"><img src="'+d.img+'" alt="'+d.scelta+'" style="max-width:100%;max-height:126px;object-fit:contain"></div>':'')+
      '<div style="font-size:12px;color:#7a8394;text-transform:uppercase;letter-spacing:.04em;font-weight:700;margin-bottom:4px">Miglior '+d.singolare+'</div>'+
      '<div style="font-size:16px;font-weight:750;color:#101828;line-height:1.25;margin-bottom:12px">'+d.scelta+'</div>'+
      '<a href="'+d.url+'" target="_blank" rel="noopener" style="display:block;text-align:center;background:linear-gradient(135deg,#F04518,#FE6E2A);color:#fff;text-decoration:none;font-weight:700;font-size:14px;padding:11px;border-radius:99px">Scopri perché su PickForMe</a>'+
      '</div>';
  } else {
    body='<div style="padding:15px"><a href="'+BASE+'/?ref=widget" target="_blank" rel="noopener" style="color:#101828;text-decoration:none;font-weight:650">Trova il prodotto giusto per te su PickForMe</a></div>';
  }
  box.innerHTML=head+body;
  s.parentNode.insertBefore(box,s);
})();